# Setup
title:        Propiedad intelectual y derechos humanos. Hacia un sistema de derechos de autor que promueva los derechos culturales.
tagline:      Presentación del libro y conferencia en la Feria del Libro Juan Filloy (Río Cuarto)
baseurl:      "https://pewen.github.io/piydh"
paginate:     1
encoding:     utf-8

# About/contact
author:
  name:       dbellomo
  url:        http://yourhomepage.com 

# Gems
#gems:
#  - jekyll-paginate

#Others
markdown: kramdown
